services:
  # Nama service diganti jadi uas-statis agar dibaca oleh GitHub Actions
  uas-statis:
    image: zaidanaliffirdaus/uas-statis:latest
    container_name: uas-statis
    ports:
      - "80:80"
    restart: always

  # Nama service diganti jadi uas-dinamis agar dibaca oleh GitHub Actions
  uas-dinamis:
    image: zaidanaliffirdaus/uas-dinamis:latest
    container_name: uas-dinamis
    ports:
      - "3000:80"
    environment:
      DATABASE_HOST: uas-mariadb
      MYSQL_DATABASE: uas_zaidan_db
      MYSQL_USER: zaidan_user
      MYSQL_PASSWORD: password_zaidan_123
    depends_on:
      uas-mariadb:
        condition: service_healthy
    restart: always

  uas-mariadb:
    image: mariadb:11
    container_name: uas-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password_123
      MYSQL_DATABASE: uas_zaidan_db
      MYSQL_USER: zaidan_user
      MYSQL_PASSWORD: password_zaidan_123
    volumes:
      - db_data:/var/lib/mysql
      - ./database/users.sql:/docker-entrypoint-initdb.d/database.sql:ro
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "zaidan_user", "-ppassword_zaidan_123"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  db_data: