version: '3.8'

services:
  # Nama service diganti jadi uas-statis agar dibaca oleh GitHub Actions
  uas-statis:
    image: zaidanaliffirdaus/uas-statis:latest
    container_name: uas-statis
    ports:
      - "80:80"
    restart: always

  # Nama service diganti jadi uas-dinamis agar dibaca oleh GitHub Actions
  uas-dinamis:
    image: zaidanaliffirdaus/uas-dinamis:latest
    container_name: uas-dinamis
    ports:
      - "3000:80"
    environment:
      DATABASE_HOST: uas-mariadb # Menunjuk ke container name mariadb
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    depends_on:
      uas-mariadb:
        condition: service_healthy
    restart: always

  uas-mariadb:
    image: mariadb:11
    container_name: uas-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./web-dinamis/database.sql:/docker-entrypoint-initdb.d/database.sql:ro
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  db_data: