name: Deploy Web Dinamis

on:
  push:
    branches:
      - main # Memanggil otomatisasi saat kamu push ke branch main
    paths:
      - 'web-dinamis/**' # Hanya berjalan jika ada perubahan di folder web-dinamis

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/uas-dinamis:latest ./web-dinamis

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/uas-dinamis:latest

      - name: Deploy to AWS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/uas-2388010038
            git pull origin main
            docker compose pull uas-dinamis
            docker compose up -d --no-deps uas-dinamis