script: |
            cd /home/ubuntu/uas-2388010038
            
            # AMANKAN INI: Tarik perubahan file docker-compose/nginx dari github ke server
            git pull origin main
            
            # Pull image baru dan naikkan service
            docker compose pull web-dinamis
            docker compose up -d --no-deps web-dinamis