script: |
            cd /home/ubuntu/uas-2388010038
            
            # AMANKAN INI: Tarik perubahan dari github ke server
            git pull origin main
            
            # Pull image baru dan naikkan service
            docker compose pull web-statis
            docker compose up -d --no-deps web-statis